# .gitlab-ci.yml

stages:
  - build
  - test

build:
  stage: build
  script: echo Building ... && sleep 10 && echo Done!

test1:
  stage: test
  script: echo Test1!

test2:
  stage: test
  script: echo Test2!