stages:
  - deploy prod
  - test prod

deploy prod:
  stage: deploy prod
  when: manual
  allow_failure: false
  # allow_failure: true
  script:
    - echo Deploy ...

test prod:
  stage: test prod
  script:
    - echo Test ...