image: node:18

job:
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .yarn-cache
  script:
    - yarn install --frozen-lockfile --cache-folder .yarn-cache --prefer-offline
    - yarn build
